# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Demo

on:
  push:
    branches: ["PART_1_and_2"]
  pull_request:
    branches: ["PART_1_and_2"]

jobs:
  buids:
      name: Node steps
      runs-on: ubuntu-latest
      steps:
        - run: echo ${{ github.ref_name }}
        - run: echo ${{ github.head_ref }}
        # - name: buils web app
        #   run : |
        #     echo "build web app"
        #     sleep 10s
        # - name: buils web app1
        #   run : |
        #     echo "build web app"
        #     sleep 10s         
        # - name: buils web app2
        #   run : |
        #     echo "build web app"
        #     sleep 10s   
        - uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
            owner: techay-mihir-simform
            repo: frontend_react 
            github_token: ${{ secrets.G_ACCESS_TOKEN }}
            workflow_file_name: dispatch.yml
            ref: main
            wait_workflow: true
            client_payload: '{"ref": "${{ github.ref_name }}" }'
        # - run: sleep 100
        - run: echo "working and tested"
#         - name: Repository Dispatch
#           #uses: peter-evans/repository-dispatch@v2
#           uses: convictional/trigger-workflow-and-wait@v1.6.1
#           with:
#             owner: techay-mihir-simform
#             repo: frontend_react 
#             github_token: ${{ secrets.G_ACCESS_TOKEN }}
#             workflow_file_name: root.yml
#             ref: main
#             wait_workflow: true
# #             client_payload: '{"sha": "test"}' 
#         - run: |
#             echo " ${{ github.ref_name }} "
#       steps:
#         - name: Dispatch an action and get the run ID
#           uses: codex-/return-dispatch@v1
#           id: return_dispatch
#           with:
#             token: ${{ secrets.G_ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
#             ref: main # or refs/heads/target_branch
#             repo: frontend_react 
#             owner: techay-mihir-simform
#             workflow: root.yml
#             workflow_inputs: '{ "distinct_id": "testtest" }' # Optional
#             workflow_timeout_seconds: 120 # Default: 300

# name: Action Test
# on:
#   pull_request:
#   push:

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - run: npm i  --prefix server/
#       - name: Dispatch and return Run ID
#         id: return_dispatch
#         uses: ./
#         with:
#           token: ${{ secrets.G_ACCESS_TOKEN }}
#           ref: PART_1_and_2
#           repo: project_mern_memories
#           owner: techay-mihir-simform
#           workflow: dispatch.yml
#           workflow_inputs: '{"cake":"delicious"}'
#           workflow_timeout_seconds: 30
#       - name: Evaluate that the Run ID output has been set
#         run: |
#           if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
#             echo "Failed to return Run ID"
#             exit 1
#           fi
#       - name: Output fetched Run ID
#         run: echo ${{ steps.return_dispatch.outputs.run_id }}
